# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'paint_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(920, 641)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        icon = QIcon()
        icon.addFile(u":/images/open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad.setIcon(icon)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon1 = QIcon()
        icon1.addFile(u":/images/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        self.actionPen.setCheckable(True)
        self.actionPen.setChecked(False)
        icon2 = QIcon()
        icon2.addFile(u":/icons/ico/pencil.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPen.setIcon(icon2)
        self.actionErase = QAction(MainWindow)
        self.actionErase.setObjectName(u"actionErase")
        self.actionErase.setCheckable(True)
        self.actionErase.setChecked(False)
        icon3 = QIcon()
        icon3.addFile(u":/icons/ico/clean.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionErase.setIcon(icon3)
        self.actionPipette = QAction(MainWindow)
        self.actionPipette.setObjectName(u"actionPipette")
        self.actionPipette.setCheckable(True)
        self.actionPipette.setChecked(False)
        icon4 = QIcon()
        icon4.addFile(u":/icons/ico/pipette.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPipette.setIcon(icon4)
        self.actionColor = QAction(MainWindow)
        self.actionColor.setObjectName(u"actionColor")
        icon5 = QIcon()
        icon5.addFile(u":/icons/ico/paint.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionColor.setIcon(icon5)
        self.actionPlus = QAction(MainWindow)
        self.actionPlus.setObjectName(u"actionPlus")
        icon6 = QIcon()
        icon6.addFile(u":/icons/ico/plus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPlus.setIcon(icon6)
        self.actionMinus = QAction(MainWindow)
        self.actionMinus.setObjectName(u"actionMinus")
        icon7 = QIcon()
        icon7.addFile(u":/icons/ico/minus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMinus.setIcon(icon7)
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        icon8 = QIcon()
        icon8.addFile(u":/images/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionImport.setIcon(icon8)
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionUndo.setEnabled(False)
        self.actionUndo.setVisible(False)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionNewBody = QAction(MainWindow)
        self.actionNewBody.setObjectName(u"actionNewBody")
        self.actionNewCoat = QAction(MainWindow)
        self.actionNewCoat.setObjectName(u"actionNewCoat")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1344, 1344))
        self.scrollAreaWidgetContents.setMinimumSize(QSize(1344, 1344))
        self.scrollAreaWidgetContents.setMaximumSize(QSize(1344, 1344))
        self.scrollAreaWidgetContents.setSizeIncrement(QSize(1, 1))
        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.grid = QGridLayout()
        self.grid.setSpacing(0)
        self.grid.setObjectName(u"grid")

        self.gridLayout.addLayout(self.grid, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.horizontalLayout.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 920, 22))
        self.menubar.setAutoFillBackground(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionPen)
        self.toolBar.addAction(self.actionErase)
        self.toolBar.addAction(self.actionPipette)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlus)
        self.toolBar.addAction(self.actionMinus)
        self.toolBar.addAction(self.actionColor)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MC Paint", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"pen", None))
#if QT_CONFIG(tooltip)
        self.actionPen.setToolTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u0442\u044c", None))
#endif // QT_CONFIG(tooltip)
        self.actionErase.setText(QCoreApplication.translate("MainWindow", u"erase", None))
#if QT_CONFIG(tooltip)
        self.actionErase.setToolTip(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0435\u0440\u0435\u0442\u044c", None))
#endif // QT_CONFIG(tooltip)
        self.actionPipette.setText(QCoreApplication.translate("MainWindow", u"pipette", None))
#if QT_CONFIG(tooltip)
        self.actionPipette.setToolTip(QCoreApplication.translate("MainWindow", u"\u0421\u043a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u0446\u0432\u0435\u0442", None))
#endif // QT_CONFIG(tooltip)
        self.actionColor.setText(QCoreApplication.translate("MainWindow", u"Color", None))
#if QT_CONFIG(tooltip)
        self.actionColor.setToolTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0446\u0432\u0435\u0442", None))
#endif // QT_CONFIG(tooltip)
        self.actionPlus.setText(QCoreApplication.translate("MainWindow", u"Plus", None))
#if QT_CONFIG(tooltip)
        self.actionPlus.setToolTip(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u0438\u0431\u043b\u0438\u0437\u0438\u0442\u044c", None))
#endif // QT_CONFIG(tooltip)
        self.actionMinus.setText(QCoreApplication.translate("MainWindow", u"Minus", None))
#if QT_CONFIG(tooltip)
        self.actionMinus.setToolTip(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u0434\u0430\u043b\u0438\u0442\u044c", None))
#endif // QT_CONFIG(tooltip)
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"\u0418\u043c\u043f\u043e\u0440\u0442 \u0444\u043e\u043d\u0430", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"\u042d\u043a\u0441\u043f\u043e\u0440\u0442", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0432\u0442\u043e\u0440\u0438\u0442\u044c", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        self.actionNewBody.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043b\u043e", None))
        self.actionNewCoat.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043b\u0430\u0449", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0437\u0434\u0430\u0442\u044c", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0430\u0439\u043b", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"\u0421\u043f\u0440\u0430\u0432\u043a\u0430", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

